/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.clsSeguridad;
import Controlador.clsBitacora;
import Controlador.clsPerfil;
import Controlador.Peliculas;
import Controlador.clsUsuarioConectado;
import Modelo.BitacoraDAO;
import Modelo.Conexion;
import Modelo.PeliculasDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;




/**
 *
 * @author marlo
 */
public class frmPeliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPeliculas
     */
    public frmPeliculas() {
        initComponents();
        llenadoDeTablas();
    }
    
    
     private clsBitacora crearBitacora(String accion) {
    clsBitacora bitacora = new clsBitacora();

    try {
        BitacoraDAO dao = new BitacoraDAO();

        // Usuario conectado (este era tu error principal)
        bitacora.setUsucodigo(1);
        int usuario = 1; // valor por defecto

        try {
        usuario = clsUsuarioConectado.getUsuId();
        } catch (Exception e) {
    System.out.println("Usuario no definido, usando default");
    }

bitacora.setUsucodigo(usuario);

        // Código de aplicación (puedes dejar fijo si no tienes sistema de apps)
        bitacora.setAplcodigo(1);

        // Fecha actual
        bitacora.setBitfecha(dao.fechaActual());

        // IP y nombre del equipo
        bitacora.setBitip(java.net.InetAddress.getLocalHost().getHostAddress());
        bitacora.setBitequipo(java.net.InetAddress.getLocalHost().getHostName());

        // Acción
        bitacora.setBitaccion(accion);

    } catch (Exception e) {
        e.printStackTrace();
    }

    return bitacora;
}
     
     
     
    public void llenadoDeTablas() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Clasificacion");
    modelo.addColumn("Genero");
    modelo.addColumn("Subtitulado");
    modelo.addColumn("Idioma");
    modelo.addColumn("Precio");

    tablaPeliculas.setModel(modelo);

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Consulta peliculas");

    List<Peliculas> lista = dao.obtenerTodos(bitacora);

    String[] dato = new String[7]; 
    for (Peliculas e : lista) {
        dato[0] = String.valueOf(e.getIdPeliculas());
        dato[1] = e.getNombre();
        dato[2] = e.getClasificacion();
        dato[3] = e.getGenero();
        dato[4] = e.getSubtitulado();
        dato[5] = e.getIdioma();
        dato[6] = String.valueOf(e.getPrecio());
        modelo.addRow(dato);
    }
}
    
    public void limpiarTextos()
    {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtClasificacion.setText("");
        txtGenero.setText("");
        txtSubtitulado.setText("");
        txtIdioma.setText(""); 
        txtPrecio.setText(""); 
    }
     
     
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtClasificacion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        txtSubtitulado = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID :");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Clasificacion");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID A BUSCAR:");

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPeliculas", "Nombre", "Clasificacion", "Genero", "Subtitulado", "Idioma", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaPeliculas);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("//-----------------------------------------PELICULAS------------------------------------------\\\\");

            jLabel6.setText("Marlon Rubén De León Gonzá   9959-19-460");

            jLabel7.setText("Meilyn Juleisy Garci Lima 9959-23-17838");

            jLabel8.setText("Genero:");

            jLabel9.setText("Subtitulado:");

            jLabel10.setText("Idioma:");

            jLabel11.setText("Precio:");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdioma)
                                            .addComponent(txtSubtitulado)
                                            .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtClasificacion)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(txtCodigo))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnRegistrar)
                                        .addComponent(btnLimpiar))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEliminar)
                                        .addComponent(btnModificar))))))
                    .addGap(48, 48, 48)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(0, 55, Short.MAX_VALUE))
                        .addComponent(jScrollPane1))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtSubtitulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegistrar)
                        .addComponent(btnModificar))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnLimpiar))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnBuscar)
                    .addGap(15, 15, 15))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Complete los campos");
        return;
    } 
        if(txtCodigo.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Ingrese ID");
    return;
}

    Peliculas peli = new Peliculas();
    peli.setIdPeliculas(Integer.parseInt(txtCodigo.getText()));
    peli.setNombre(txtNombre.getText());
    peli.setClasificacion(txtClasificacion.getText());
    peli.setGenero(txtGenero.getText());
    peli.setSubtitulado(txtSubtitulado.getText());
    peli.setIdioma(txtIdioma.getText());
    double precio;

try {
    precio = Double.parseDouble(txtPrecio.getText());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Precio inválido");
    return;
}

peli.setPrecio(precio);

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Insertar pelicula");

    dao.insertar(peli, bitacora); // ✔ correcto

    JOptionPane.showMessageDialog(null, "Película registrada");

    llenadoDeTablas();
    limpiarTextos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Seleccione un registro");
        return;
    }

    
    Peliculas peli = new Peliculas();
    peli.setIdPeliculas(Integer.parseInt(txtCodigo.getText()));
    peli.setNombre(txtNombre.getText());
    peli.setClasificacion(txtClasificacion.getText());
    peli.setGenero(txtGenero.getText());
    peli.setSubtitulado(txtSubtitulado.getText());
    peli.setIdioma(txtIdioma.getText());
    double precio;

try {
    precio = Double.parseDouble(txtPrecio.getText());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Precio inválido");
    return;
}

peli.setPrecio(precio);
    

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Modificar pelicula");
    dao.actualizar(peli, bitacora);

    JOptionPane.showMessageDialog(null, "Película modificada");

    llenadoDeTablas();
    limpiarTextos();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTextos();
        habilitarBotones();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if(txtCodigo.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese un código");
        return;
    }

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Eliminar pelicula");

    dao.eliminar(Integer.parseInt(txtCodigo.getText()), bitacora); // ✔ correcto

    JOptionPane.showMessageDialog(null, "Película eliminada");

    llenadoDeTablas();
    limpiarTextos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese un ID");
        return;
    }

    int id = Integer.parseInt(txtBuscar.getText());

    PeliculasDAO dao = new PeliculasDAO();
    clsBitacora bitacora = crearBitacora("Buscar pelicula");

    List<Peliculas> lista = dao.obtenerTodos(bitacora);

    
    boolean encontrado = false;
    for(Peliculas peli : lista){
        if(peli.getIdPeliculas() == id){

        txtCodigo.setText(String.valueOf(peli.getIdPeliculas()));
        txtNombre.setText(peli.getNombre());
        txtClasificacion.setText(peli.getClasificacion());
        txtGenero.setText(peli.getGenero());
        txtSubtitulado.setText(peli.getSubtitulado());
        txtIdioma.setText(peli.getIdioma());
        txtPrecio.setText(String.valueOf(peli.getPrecio()));

        encontrado = true;
        break;
    }  
        
    }//GEN-LAST:event_btnBuscarActionPerformed
    if(!encontrado){
    JOptionPane.showMessageDialog(null, "Película no encontrada");
}
    }
    
    
    public void habilitarBotones(){
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }
    public void desHabilitarBotones()
    {
        btnRegistrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    } 
    
    
    public void esperar5min(){
        try {
            //Ponemos a "Dormir" el programa durante los minutos que querramos
            Thread.sleep(5*60*1000);
        } catch (Exception e) {
            System.out.println(e);}
    }
    
    /**
     * @param args the command line arguments
     */
    //este de aqui ayuda a hacer visible la ventana
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new frmPeliculas().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtitulado;
    // End of variables declaration//GEN-END:variables
}
